import fs from 'fs';
import path from 'path';

const CURSOR_DIR = '.cursor';
const RULES_FILE = '.cursor/rules';
const CONTEXT_FILE = '.delta/cursor-context.md';

export interface CursorSetupResult {
  cursorDetected: boolean;
  rulesWritten: boolean;
  rulesPath: string;
}

/**
 * Detect if this is a Cursor project and write optimized rules.
 * Cursor reads .cursor/rules automatically on every session.
 */
export function setupCursorIntegration(
  projectRoot: string
): CursorSetupResult {
  const cursorDir = path.join(projectRoot, CURSOR_DIR);
  const rulesPath = path.join(projectRoot, RULES_FILE);

  // Detect Cursor project
  const cursorDetected = fs.existsSync(cursorDir);

  if (!cursorDetected) {
    // Create .cursor/ directory anyway - user may be setting up Cursor
    fs.mkdirSync(cursorDir, { recursive: true });
  }

  // Write Delta rules for Cursor
  const rules = buildCursorRules(projectRoot);
  fs.writeFileSync(rulesPath, rules, 'utf-8');

  return {
    cursorDetected,
    rulesWritten: true,
    rulesPath,
  };
}

function buildCursorRules(projectRoot: string): string {
  const contextFile = path.join(projectRoot, CONTEXT_FILE);
  const contextExists = fs.existsSync(contextFile);

  return [
    '# ∆ Delta Context Engine - Cursor Integration',
    '# Auto-generated by: delta cursor-init',
    '# Do not edit manually - re-run delta cursor-init to update',
    '',
    '## Context Optimization',
    '',
    'Before answering any coding question:',
    '1. Check if `.delta/cursor-context.md` exists',
    '2. If it exists, use its contents as the primary context for this task',
    '3. The file contains only the changed files and their direct dependencies',
    '4. Do not re-read files already summarized in the context file',
    '',
    '## Token Efficiency Rules',
    '',
    '- Trust the symbol maps in cursor-context.md - they show all exports/imports',
    '- Trust the summaries - they describe each file accurately',
    '- Only request full file content if a specific implementation detail is needed',
    '- Changed files (marked ✅) are provided in full - use them directly',
    '',
    '## How to Use Delta with Cursor',
    '',
    '```',
    '# Before starting a task, run in terminal:',
    'delta run "your task description"',
    '',
    '# This updates .delta/cursor-context.md with optimized context',
    '# Then ask Cursor your question - it will use the optimized context',
    '```',
    '',
    contextExists
      ? `## Current Context\n\nSee: \`.delta/cursor-context.md\` (last updated by delta run)`
      : `## Setup\n\nRun \`delta run "your task"\` to generate optimized context.`,
  ].join('\n');
}

export function writeCursorContext(
  projectRoot: string,
  formattedPayload: string
): void {
  const contextPath = path.join(projectRoot, CONTEXT_FILE);
  const deltaDir = path.join(projectRoot, '.delta');

  if (!fs.existsSync(deltaDir)) {
    fs.mkdirSync(deltaDir, { recursive: true });
  }

  const content = [
    '<!-- ∆ Delta Context - auto-generated, do not edit -->',
    `<!-- Generated: ${new Date().toISOString()} -->`,
    '',
    formattedPayload,
  ].join('\n');

  fs.writeFileSync(contextPath, content, 'utf-8');
}

export { CONTEXT_FILE, RULES_FILE };